### ISSUE TITLE
problem using program=doesntexist

### ISSUE THREAD

**Issue by fheidrich** [lachlanhurst/SCNTechniqueTest#2]
Hi, trying SCNTechniqueTest on Xcode 10.2

I get the following error on the console when I run it:
2019-08-13 12:32:58.354171-0700 SCNTechniqueGlow[91749:3168796] [SceneKit] Error: failed to load resource named doesntexist.vsh
2019-08-13 12:32:58.354559-0700 SCNTechniqueGlow[91749:3168796] [SceneKit] Error: failed to load resource named doesntexist.fsh

I tried removing program from the plist file (but fails to build, program seems like a required filed)

Any clues how to proceed ?
Thanks

**Comment by lachlanhurst** [comment]
The bug that existed in SceneKit that required a program name (despite never using it) was fixed some time ago. I should update this repo for the latest Xcode/iOS.

However, the fact it is mentioning `.vsh` and `.fsh` resources seems to indicate it's trying to use OpenGL. All the shaders in this repo use Metal; so even if you fix this issue it still wont work. Are you forcing SceneKit to use OpenGL or running on a simulator? Note: next version of Xcode will support Metal in the simulator, current release version doesn't.

**Comment by fheidrich** [comment]
Thanks, running on the device worked!
